# 檔案位置
input_file = "samples/sample_scan.txt"
output_file = "reports/Security_Report.md"

# 讀取弱掃檔案
with open(input_file, "r", encoding="utf-8") as file:
    content = file.read()

# 建立 Markdown 報告
report = f"""# Security Report

## Scan Result
```
{content}
```

---

Generated by AI Security Report Assistant
"""

# 寫入報告
with open(output_file, "w", encoding="utf-8") as file:
    file.write(report)

print("✅ 報告已產生！")
print(f"輸出位置：{output_file}")