from pathlib import Path

# File paths
input_file = Path("samples/sample_scan.txt")
output_file = Path("reports/Security_Report.md")

# Make sure the reports folder exists
output_file.parent.mkdir(parents=True, exist_ok=True)

# Read scan result
with input_file.open("r", encoding="utf-8") as file:
    content = file.read()

# Generate Markdown report
report = f"""# Security Report

## Scan Result

```txt
{content}
```

---

Generated by AI Security Report Assistant
"""

# Write report
with output_file.open("w", encoding="utf-8") as file:
    file.write(report)

print("Report generated successfully.")
print(f"Output file: {output_file}")